//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyOrderPdf
    {
        public int CompanyOrderPdf1 { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string RndKey { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
