//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementOperation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockEntities : DbContext
    {
        public StockEntities()
            : base("name=StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AppUsers> AppUsers { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyOrderPdf> CompanyOrderPdf { get; set; }
        public virtual DbSet<County> County { get; set; }
        public virtual DbSet<DeletedCompany> DeletedCompany { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<PayInfo> PayInfo { get; set; }
        public virtual DbSet<ProductDetails> ProductDetails { get; set; }
        public virtual DbSet<ProductMainPage> ProductMainPage { get; set; }
        public virtual DbSet<ProductPhotograph> ProductPhotograph { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<RandomKeyResetPassword> RandomKeyResetPassword { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<SupportNotification> SupportNotification { get; set; }
        public virtual DbSet<UserCart> UserCart { get; set; }
    }
}
