//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.ProductDetails = new HashSet<ProductDetails>();
            this.ProductMainPage = new HashSet<ProductMainPage>();
            this.ProductPhotograph = new HashSet<ProductPhotograph>();
            this.UserCart = new HashSet<UserCart>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public Nullable<double> NewPrice { get; set; }
        public Nullable<byte> CategoryID { get; set; }
        public Nullable<int> ProductStock { get; set; }
        public Nullable<int> CriticalStock { get; set; }
        public Nullable<int> StorageID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> CargoPay { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetails> ProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMainPage> ProductMainPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhotograph> ProductPhotograph { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCart> UserCart { get; set; }
    }
}
